FROM golang:1.27.2-alpine@sha256:85dc1069ac644ea3c527b177303a406eb3358192816cd7f9e5848eb658851673 AS build
ENV CGO_ENABLED=0 GOWORK=off GOFLAGS=-p=2
WORKDIR /src
RUN wget -qO /tmp/source.tar.gz https://github.com/prometheus/prometheus/archive/5241a27fe3c6983549fccc32f6e65917408c63cd.tar.gz && tar -xzf /tmp/source.tar.gz --strip-components=1
RUN go build -o /prometheus ./cmd/prometheus && go build -o /promtool ./cmd/promtool
RUN go build -ldflags="-X github.com/prometheus/common/version.Version=3.15.0 -X github.com/prometheus/common/version.Revision=5241a27fe3c6983549fccc32f6e65917408c63cd" -o /prometheus ./cmd/prometheus
FROM prom/prometheus:v3.15.0@sha256:efd719c99d83b060d9daefdcf00360461adf279f45ef5391f8d111892118753e
COPY --from=build /prometheus /bin/prometheus
COPY --from=build /promtool /bin/promtool
USER 10001:10001
